### ISSUE TITLE
Permission To Include On CurseForge Modpack

### ISSUE THREAD

**Issue by Fyoncle** [First-Name-Last-Name/Swimming-Horses#1]
Hello! I am the owner of Elysium Days modpack, i wanna release my modpack also on curseforge any sooner, but i need your permission to include this mod on a curseforge hosted modpack!

**Comment by First-Name-Last-Name** [comment]
Hey there! Feel free to include Swimming Horses in your modpacks, as long as proper credit is given. A referral to the mod on Modrinth would be optimal.

**Comment by Fyoncle** [comment]
> Hey there! Feel free to include Swimming Horses in your modpacks, as long as proper credit is given. A referral to the mod on Modrinth would be optimal.

Thanks!
